from cassandra.cluster import Cluster
cluster = Cluster(['172.31.35.21'], port=9042)
session = cluster.connect()
statesToInsert = {
'Arkansas',
'Alabama',
'Arizona',
'Alaska',
'California',
'Colorado',
'Connecticut',
'Delaware',
'Florida',
'Georgia',
'Hawaii',
'Iowa',
'Idaho',
'Illinois',
'Indiana',
'Kansas',
'Kentucky',
'Louisiana',
'Massachusetts',
'Maryland',
'Maine',
'Michigan',
'Minnesota',
'Missouri',
'Mississippi',
'Montana',
'NorthCarolina',
'NorthDakota',
'Nebraska',
'NewHampshire',
'NewJersey',
'NewMexico',
'Nevada',
'NewYork',
'Ohio',
'Oklahoma',
'Oregon',
'Pennsylvania',
'RhodeIsland',
'SouthCarolina',
'SouthDakota',
'Tennessee',
'Texas',
'Utah',
'Virginia',
'Vermont',
'Washington',
'Wisconsin',
'WestVirginia',
'Wyoming'
}                                                                                                                                                                  
for item in statesToInsert:                                                                                                        
#insert into the table                                                                                                                                        
	session.execute("DROP KEYSPACE " + item +";")
cluster.shutdown()